### PR TITLE
General improvements

### PR DESCRIPTION
**Pull request by tysongach**
- Remove `Thorfile`
  - This removes all questions/prompts during a new Middleman project initialization. We are only asking two questions, but to a new Middleman user, I think they can be confusing and they hinder a seamless, straightforward process to getting started. This simplifies the UX and our maintenance of this repo.
  - ~~LiveReload is commonly used, so let’s just have that setup by default.~~
  - This is an assumption—and I could be totally wrong—but I’m not sure the everyday Middleman user is using Rack Middleware, so let’s make sure this is covered in the docs/guides, but remove it from a new project initialization.
- Remove comments from `gitignore` template
- ~~Add `middleman-autoprefixer`~~
  - ~~Autoprefixer has become a standard for automated CSS prefixing. This sets it up for everyone out of the box.~~
- Clean up layout
- Clean up `Gemfile` and `config.rb`
  - Remove comments.
  - ~~Activate `minify_css` and `minify_javascript` extensions.~~

I’ll admit that there are some opinions with these changes, so I’m happy to have a discussion!

~~Note: We’ll want to remove the mention of the `Thorfile` in the template here: https://middlemanapp.com/advanced/project_templates/#thor-template~~

### CODE REVIEW

**Comment by tysongach** [comment]
@tdreyno Mind taking a 👀 at this when you have a chance?

**Comment by tdreyno** [comment]
Yeah. I hate livereload :) But I'm cool with this.

Mostly, this is just what I use to test the `Thor` support :) Can we keep it with no questions?

**Comment by tysongach** [comment]
> Yeah. I hate livereload :)

Ha! No worries. Let‘s leave it in with Thor, then. Now that we have the external pipeline feature, more people could be using other tooling instead of LiveReload.

**Comment by tysongach** [comment]
Updated with changes discussed above. I also reverted on my addition of `middleman-autoprefixer`; we can let developers choose their tools.

**Comment by tdreyno** [comment]
I liked the comments, I think it was a nice prompt for users to discover other features. I'm also totally cool with defaulting to autoprefixer since it's a core project

**Comment by tysongach** [comment]
@tdreyno Updated.

**Pull request merged**
