### PR TITLE
Update Gemfile

### LINKED ISSUE #2463: css 404 error after build
Hi there, 

I'm building my first middleman site and am experiencing some issues with the stylesheet link. The css was running before, but after running 'bundle exec middleman build', I am getting a 404 in the stylesheets. I've added a default to the config.rb file, tried changing the file names etc but nothing seems to be working. 

Any advice? I'm struggling a lot.

Thanks!

### PR DESCRIPTION
**Pull request by johnsorrentino**
Unpin `middleman` and `middleman-autoprefixer` to resolve https://github.com/middleman/middleman/issues/2463

### CODE REVIEW

**Comment by jankoegel** [comment]
Can we get this merged? It was very confusing to start a new Middleman project and run into the error from [middleman#2463](https://github.com/middleman/middleman/issues/2463) - middleman seemed broken from the start. Took me a while to find the fix here.
Would be much appreciated, thanks!

**Comment by gbirchmeier** [comment]
Just puzzled my way through this.  As a noob to this project, it was a pain in the butt.  Dunno why this isn't merged yet.

**Comment by johnsorrentino** [comment]
Hey @tdreyno, thoughts on this change?

**Comment by tdreyno** [comment]
@johnsorrentino I think we still need to keep the ranges. The middleman one shouldn't be causing issues. It seems the above link is about middleman-autoprefixer needing to be 3.x instead of 2.x?


These two comments seem to have it right. So: 

```
ruby '>= 2.7', '< 3.0'

gem 'middleman', '~> 4.4'
gem 'middleman-autoprefixer', '~> 3.0'
```

**Comment by gbirchmeier** [comment]
@tdreyno - as long as you put out a release of middleman that can do `init` then `build` without erroring out, you can choose whichever solution you want.

See https://github.com/middleman/middleman/issues/2613 for what I ran into 2 weeks ago as a noob to this project.  The latest release is broken.

**Comment by tdreyno** [comment]
@gbirchmeier you are not welcome here if you cannot be civil. This is a 15 year old project which hasn't had a major release in 7 years. I don't appreciate the entitled attitude. Either you can help the community contribute fixes, like John is doing, or you can leave.

**Comment by gbirchmeier** [comment]
I apologize for my tone, which as I reread it does seem more out-of-line than I intended.

I also run an open-source project, and people have been entitled jerks to me, so I fully apologize and am embarrassed to be on the other side of that.

When you are able, I look forward to a minor release that corrects the `init` then `build` error.

**Comment by jagthedrummer** [comment]
Here's a PR that gets the starter project working for me. (Everything seems to work fine with ruby 3.1.2, so I left out the bits about pinning ruby.)

https://github.com/middleman/middleman-templates-default/pull/15

**Pull request closed without merging**
